server:
  port: 31000
spring:
  application:
    name: xc‐service‐manage‐cms‐client
  data:
    mongodb:
      uri: mongodb://120.78.200.139:27017
      database: xc_cms
  rabbitmq:
    host: 192.168.56.110
#    host: 120.78.200.139
    port: 5672
    username: guest
    password: guest
    virtual-host: /
xuecheng:
  mq:
    #cms客户端监控的队列名称（不同的客户端监控的队列不能重复）
    queue: queue_cms_postpage_01
    #此routingKey为门户站点ID
    routingkey: 5a751fab6abb5044e0d19ea1
